apiVersion: gateway.tsb.tetrate.io/v2
kind: Group
metadata:
  tenant: tetrate-trader
  organization: tetrate-workshop
  workspace: accounts-workspace
  name: accounts-gateway
spec:
  displayName: accounts-gateway
  description: accounts-gateway
  namespaceSelector:
    names:
      - "*/accounts"
  configMode: BRIDGED
---
apiVersion: gateway.tsb.tetrate.io/v2
kind: IngressGateway
metadata:
  name: accounts-gw
  group: accounts-gateway
  workspace: accounts-workspace
  tenant: tetrate-trader
  organization: tetrate-workshop
spec:
  workloadSelector:
    namespace: accounts
    labels:
      app: tsb-gateway-accounts
  http:
    - name: accounts-gw
      port: 443
      hostname: "accounts.trader.cloud.zwickey.net"
      tls:
        mode: SIMPLE
        secretName: accounts-cert
      routing:
        rules:
          - route:
              host: "accounts/accounts-service.accounts.svc.cluster.local"
              port: 8080